model_args:
  char_emb_size: 50
  char_vocab: 24
  ctx_layers: 4
  dec_layers: 4
  dropout: 0.1
  ff_size: 1024
  hid_size: 512
  n_heads: 8
  sent_repr_mode: cls
  text_vocab: 8000
  tied_emb: null
  utter_layers: 4
model_type: TRANSFORMER
optim:
  args:
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-09
    label_smoothing: 0.1
    lr: 0.001
    warmup_steps: 3000
  name: ADAM
prep:
  char_min_freq: 100
  finetune_dialogs: data/merged/friends.train.tok.simpl.tsv
  max_seq_len: 50
  max_types: 8000
  no_split_toks:
  - ross
  - rachel
  - monica
  - chandler
  - phoebe
  - joey
  - gunter
  pieces: bpe
  train_dialogs: data/merged/friends.train.tok.simpl.tsv
  valid_dialogs: data/merged/friends.dev.tok.simpl.tsv
  vocab_text: data/merged/train.merged.tok.simpl.txt
trainer:
  max_chats: 120
  max_ctx: 40
  max_utters: 200
  min_ctx: 2
  min_resp_len: 5
  no_repeat: true
updated_at: '2018-12-07T15:04:20.153667'
