model_args:
  attention: dot
  char_emb_size: 50
  char_vocab: 11
  dropout: 0.2
  hid_size: 300
  n_layers: 2
  rnn_type: GRU
  text_emb_size: 300
  text_vocab: 8000
model_type: HRED
optim:
  args:
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-09
    label_smoothing: 0.1
    lr: 0.01
    warmup_steps: 500
  name: ADAM
trainer:
  characters:
  - Ross
  - Rachel
  - Monica
  - Chandler
  - Phoebe
  - Joey
  - Gunter
  max_chats: 10
  max_ctx: 10
  max_utters: 20
  min_ctx: 2
prep:
  characters:
  - <pad>
  - <unk>
  - <scene>
  - <event>
  - Ross
  - Rachel
  - Monica
  - Chandler
  - Phoebe
  - Joey
  - Gunter
  - All
  finetune_dialogs: data/friends/friends.train.tok.tsv
  max_seq_len: 50
  max_types: 8000
  no_split_toks:
  - Ross
  - Rachel
  - Monica
  - Chandler
  - Phoebe
  - Joey
  - Gunter
  pieces: bpe
  train_dialogs: data/friends/friends.train.tok.tsv
  valid_dialogs: data/friends/friends.dev.tok.tsv
  vocab_text: data/friends/friends.train.tok.txt
updated_at: '2018-11-19T22:40:36.078845'
