model_args:
  dropout: 0.2
  ff_size: 2048
  hid_size: 512
  n_heads: 8
  n_layers: 2
  text_vocab: 8000
  tied_emb: three-way
model_type: TRANSFORMER
optim:
  args:
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-09
    label_smoothing: 0.1
    lr: 0.1
    warmup_steps: 4000
  name: ADAM
trainer:
  max_chats: 10
  max_ctx: 10
  max_utters: 20
  min_ctx: 2
prep:
  finetune_dialogs: data/friends/friends.train.tok.tsv
  max_seq_len: 50
  max_types: 8000
  no_split_toks:
  - Ross
  - Rachel
  - Monica
  - Chandler
  - Phoebe
  - Joey
  - Gunter
  pieces: bpe
  train_dialogs: data/friends/friends.train.tok.tsv
  valid_dialogs: data/friends/friends.dev.tok.tsv
  vocab_text: data/friends/friends.train.tok.txt
updated_at: '2018-11-19T22:42:56.191736'
