model_args:
  dropout: 0.2
  ff_size: 2048
  hid_size: 512
  n_heads: 8
  n_layers: 2
  text_vocab: 8000
  tied_emb: three-way
model_type: TRANSFORMER
optim:
  args:
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-09
    label_smoothing: 0.1
    lr: 0.1
    warmup_steps: 200
  name: ADAM
trainer:
  characters:
  - Ross
  - Rachel
  - Monica
  - Chandler
  - Phoebe
  - Joey
  - Gunter
  max_chats: 10
  max_ctx: 10
  max_utters: 20
  min_ctx: 2
updated_at: '2018-11-19T22:42:56.191736'
