model_args:
  dropout: 0.2
  ff_size: 1024
  hid_size: 300
  n_heads: 5
  n_layers: 4
  text_vocab: 8000
  tied_emb: three-way
model_type: TRANSFORMER
optim:
  args:
    betas:
    - 0.9
    - 0.98
    eps: 1.0e-09
    label_smoothing: 0.3
    lr: 0.1
    warmup_steps: 4000
  name: ADAM
trainer:
  max_chats: 100
  max_ctx: 50
  max_utters: 100
  min_ctx: 2
  min_resp_len: 5
prep:
  char_min_freq: 100
  finetune_dialogs: data/merged/friends.train.tok.simpl.tsv
  max_seq_len: 50
  max_types: 8000
  no_split_toks:
  - ross
  - rachel
  - monica
  - chandler
  - phoebe
  - joey
  - gunter
  pieces: bpe
  train_dialogs: data/merged/train.merged.tok.simpl.tsv
  valid_dialogs: data/merged/friends.dev.tok.simpl.tsv
  vocab_text: data/merged/train.merged.tok.simpl.txt
updated_at: '2018-11-19T22:42:56.191736'
